change ssh name env

diff --git a/.github/workflows/deploy_to_aws.yml b/.github/workflows/deploy_to_aws.yml
--- a/.github/workflows/deploy_to_aws.yml
+++ b/.github/workflows/deploy_to_aws.yml
@@ -62,26 +62,47 @@ jobs:
       - name: Verify artifact content
         run: ls -la ./dist/
 
-      - name: Archive build folder
-        run: tar -czf my-app.tar.gz dist
-
-      - name: Copy files to EC2
-        uses: appleboy/scp-action@v0.1.1
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_PRIVATE_KEY }}
-          source: "my-app.tar.gz"
-          target: "/home/ec2-user/my-app.tar.gz"
-
-      - name: Deploy on EC2
-        uses: appleboy/ssh-action@v0.1.1
+      - name: Create Target Directory on EC2
+        uses: appleboy/ssh-action@v0.1.6
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_PRIVATE_KEY }}
           script: |
-            tar -xzf /home/ec2-user/my-app.tar.gz -C /var/www/my-app
-            cd /var/www/my-app
-            npm install --production
-            pm2 restart my-app
+            sudo mkdir -p /var/www/myApps
+            sudo chown $USER:$USER /var/www/myApps
+
+      - name: Copy files to EC2
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_PRIVATE_KEY }}
+          target: /var/www/myApps
+          source: ./dist/*
+          debug: true
+
+      - name: Install Node.js and Restart App
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_PRIVATE_KEY }}
+          script: |
+            cd /var/www/myApps
+            # Set DEBIAN_FRONTEND to noninteractive for the script
+            export DEBIAN_FRONTEND=noninteractive
+
+            # Install Node.js if not already installed
+            if ! command -v node &> /dev/null; then
+            echo "Node.js not found, installing..."
+            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
+            sudo apt-get install -y nodejs
+            fi
+            # Ensure PM2 is available
+            if ! command -v pm2 &> /dev/null; then
+            echo "PM2 not found, installing.."
+            sudo npm install -g pm2
+            fi
+            # Restart or start the app
+            pm2 restart all || pm2 start ./index.js --name "my-app"
